INSERT INTO adresse (adresse_id, strasse, plz, ort, land, erzeugt, aktualisiert, version) VALUES(100, 'Willy-Andreas-Allee 17', '76131', 'Karlsruhe', 'DE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0);
INSERT INTO adresse (adresse_id, strasse, plz, ort, land, erzeugt, aktualisiert, version) VALUES(101, 'Willy-Andreas-Allee 17', '76131', 'Karlsruhe', 'DE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0);
INSERT INTO adresse (adresse_id, strasse, plz, ort, land, erzeugt, aktualisiert, version) VALUES(102, 'Güterweg 34', '76131', 'Karlsruhe', 'DE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0);
INSERT INTO adresse (adresse_id, strasse, plz, ort, land, erzeugt, aktualisiert, version) VALUES(103, 'Güterweg 34', '76131', 'Karlsruhe', 'DE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0);
INSERT INTO adresse (adresse_id, strasse, plz, ort, land, erzeugt, aktualisiert, version) VALUES(104, 'Singenerstraße 35', '78256', 'Steißlingen', 'DE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0);
INSERT INTO adresse (adresse_id, strasse, plz, ort, land, erzeugt, aktualisiert, version) VALUES(105, 'Singenerstraße 35', '78256', 'Steißlingen', 'DE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0);
INSERT INTO adresse (adresse_id, strasse, plz, ort, land, erzeugt, aktualisiert, version) VALUES(106, 'Uhlandstraße 119', '78224', 'Singen', 'DE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0);
INSERT INTO adresse (adresse_id, strasse, plz, ort, land, erzeugt, aktualisiert, version) VALUES(107, 'Uhlandstraße 119', '78224', 'Singen', 'DE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0);
INSERT INTO adresse (adresse_id, strasse, plz, ort, land, erzeugt, aktualisiert, version) VALUES(108, 'Königsstraße 8', '70173', 'Stuttgart', 'DE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0);
INSERT INTO adresse (adresse_id, strasse, plz, ort, land, erzeugt, aktualisiert, version) VALUES(109, 'Königsstraße 8', '70173', 'Stuttgart', 'DE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0);
INSERT INTO adresse (adresse_id, strasse, plz, ort, land, erzeugt, aktualisiert, version) VALUES(110, 'Eisenbahnstraße 57', '79098', 'Freiburg', 'DE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0);
INSERT INTO adresse (adresse_id, strasse, plz, ort, land, erzeugt, aktualisiert, version) VALUES(111, 'Eisenbahnstraße 57', '79098', 'Freiburg', 'DE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0);
INSERT INTO adresse (adresse_id, strasse, plz, ort, land, erzeugt, aktualisiert, version) VALUES(140, 'Tobleronestraße 1', '8200', 'Schaffhausen', 'CH', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0);
INSERT INTO adresse (adresse_id, strasse, plz, ort, land, erzeugt, aktualisiert, version) VALUES(141, 'Tobleronestraße 1', '8200', 'Schaffhausen', 'CH', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0);
INSERT INTO adresse (adresse_id, strasse, plz, ort, land, erzeugt, aktualisiert, version) VALUES(142, 'Alpenweg 74', '8004', 'Zürich', 'CH', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0);
INSERT INTO adresse (adresse_id, strasse, plz, ort, land, erzeugt, aktualisiert, version) VALUES(143, 'Alpenweg 74', '8004', 'Zürich', 'CH', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0);
INSERT INTO adresse (adresse_id, strasse, plz, ort, land, erzeugt, aktualisiert, version) VALUES(144, 'Seestraße 55', '8004', 'Zürich', 'CH', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0);
INSERT INTO adresse (adresse_id, strasse, plz, ort, land, erzeugt, aktualisiert, version) VALUES(145, 'Uniweg 4', '4001', 'Basel', 'CH', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0);
INSERT INTO adresse (adresse_id, strasse, plz, ort, land, erzeugt, aktualisiert, version) VALUES(146, 'Hauptstraße 98', '4001', 'Basel', 'CH', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0);
INSERT INTO adresse (adresse_id, strasse, plz, ort, land, erzeugt, aktualisiert, version) VALUES(147, 'Jodlergasse 6', '7000', 'Chur', 'CH', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0);
INSERT INTO adresse (adresse_id, strasse, plz, ort, land, erzeugt, aktualisiert, version) VALUES(170, 'Baumgarten 57', '5280', 'Braunau am Inn', 'A', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0);
INSERT INTO adresse (adresse_id, strasse, plz, ort, land, erzeugt, aktualisiert, version) VALUES(171, 'Straden 79', '5280', 'Braunau am Inn', 'A', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0);
INSERT INTO adresse (adresse_id, strasse, plz, ort, land, erzeugt, aktualisiert, version) VALUES(172, 'Rossmarkt 69', '5280', 'Braunau am Inn', 'A', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0);
INSERT INTO adresse (adresse_id, strasse, plz, ort, land, erzeugt, aktualisiert, version) VALUES(173, 'Lucasweg 36', '5010', 'Salzburg', 'A', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0);
INSERT INTO adresse (adresse_id, strasse, plz, ort, land, erzeugt, aktualisiert, version) VALUES(174, 'Salzburgerstrasse 42', '5010', 'Salzburg', 'A', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0);
INSERT INTO adresse (adresse_id, strasse, plz, ort, land, erzeugt, aktualisiert, version) VALUES(175, 'Zistelweg 32', '1220', 'Wien', 'A', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0);
